# Generated by Django 5.1.4 on 2025-03-18 07:44

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=bookings.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='draftBooking',
            fields=[
                ('id', models.CharField(default=bookings.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='allUserBookings',
            fields=[
                ('id', models.CharField(default=bookings.models.generate_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('movie_title', models.CharField(max_length=100)),
                ('show_date', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat')),
            ],
        ),
    ]
